import Header from "@/components/custom/header/Header";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider, useCart } from "./context/cart";
import AlertaCarrito from "@/components/custom/alertCarrito/AlertaCarrito";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </CartProvider>
  );
}
